[[pages]]
path = "Inicio.py"
name = "Pagina Inicial"
icon = "🏠"

[[pages]]
path = "pages/CGR.py"
name = "Cadastro Geral de Recomendações"
icon = "📝"

[[pages]]
path = "pages/Cancelamentos.py"
name = "Cancelamento de Itens"
icon = "❌"